// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTrfKpWu4XWYGZleIy_odqfvGUXZFN_XM',
    appId: '1:401967252710:web:337e8cfce49ca12e1a6727',
    messagingSenderId: '401967252710',
    projectId: 'theshophup',
    authDomain: 'theshophup.firebaseapp.com',
    storageBucket: 'theshophup.firebasestorage.app',
    measurementId: 'G-97558WDX6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXMaQ7zkARYuUF2cuvJ4L1da3H_Wz8CUE',
    appId: '1:401967252710:android:4ecc52294b0c90251a6727',
    messagingSenderId: '401967252710',
    projectId: 'theshophup',
    storageBucket: 'theshophup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOnaa7dlSEsCLgqrc3_hNDCXXe1pQ6Svw',
    appId: '1:401967252710:ios:f5aaf5a073bb4c3b1a6727',
    messagingSenderId: '401967252710',
    projectId: 'theshophup',
    storageBucket: 'theshophup.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOnaa7dlSEsCLgqrc3_hNDCXXe1pQ6Svw',
    appId: '1:401967252710:ios:f5aaf5a073bb4c3b1a6727',
    messagingSenderId: '401967252710',
    projectId: 'theshophup',
    storageBucket: 'theshophup.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTrfKpWu4XWYGZleIy_odqfvGUXZFN_XM',
    appId: '1:401967252710:web:78d98ab9c0c442321a6727',
    messagingSenderId: '401967252710',
    projectId: 'theshophup',
    authDomain: 'theshophup.firebaseapp.com',
    storageBucket: 'theshophup.firebasestorage.app',
    measurementId: 'G-691XZY5CL5',
  );
}
